### ISSUE TITLE
Suggestion of code smell: avoid long code snippets from macros

### ISSUE THREAD

**Issue by josevalim** [lucasvegi/Elixir-Code-Smells#13]
I am not sure if this would be a smell per-se, but we typically want to avoid generating a lot of code from inside macros.

In the majority of cases, macros should simply delegate to other functions that do the work. Imagine you are defining a router for a web application, where you could have macros like this:

    defmodule Routes do
      ...

      defmacro get(route, handler) do
        quote do
          route = unquote(route)
          handler = unquote(handler)

          if not is_binary(route) do
            raise ArgumentError, "route must be a binary"
          end

          if not is_atom(handler) do
            raise ArgumentError, "route must be a module"
          end

          @store_route_for_compilation {route, handler}
        end
      end
    end

The issue with the above is that, for each route define, which can be hundreds, Elixir has to expand, compile, and execute that code multiple times, which will make compilation slower. The fix is to encapsulate the functionality inside quote:

    defmodule Routes do
      ...

      defmacro get(route, handler) do
        quote do
          Routes.__define__(__MODULE__, unquote(route), unquote(handler))
        end
      end

      def __define__(module, route, handler) do
        route = unquote(route)
        handler = unquote(handler)

        if not is_binary(route) do
          raise ArgumentError, "route must be a binary"
        end

        if not is_atom(handler) do
          raise ArgumentError, "route must be a module"
        end

        Module.put_attribute(module, :store_route_for_compilation, {route, handler})
      end
    end

With the above, we reduce the code that is expanded and compiled on every invocation of the macro, and instead we dispatch to a function to do the bulk of the work.

**Comment by lucasvegi** [comment]
I think this is a code smell from the Low-level concerns category!

Following the naming conventions given to smells, what do you think about calling this one the "Large macro"?

**Comment by lucasvegi** [comment]
Actually, I think it would be better "Long macro".. so we will make an analogy with "Long function"

**Comment by josevalim** [comment]
I don’t think the issue is necessarily that the macro is large but rather that it generates too much code. For example, I could Refactor a macro to build the code in parts But the issue still exists.

Also, while a large function or a large macro would look ugly and be hard to maintain, they don’t impact how the compiler or the runtime works. This issue does.

However, I do agree it feels similar to large functions and large macros. We could say ” large code generation”, WDYT?

**Comment by lucasvegi** [comment]
I agree with you. The implications of "Long function" are more of code complexity, maintainability, readability... in short, design!

This new smell is more related to performance aspects of the code, which is why I consider it Low-level. I thought of a name that uses "Large" or "Long" because somehow that can make an analogy with other smell names.

I really liked "Large code generation". It allows for the analogy but also describes some of the implications. Great!

**Comment by lucasvegi** [comment]
Hi Valim,

I added the smell to the catalog. As I'm not yet fully familiar with macros, I tried to rely heavily on snippets from our discussion to write the documentation.

What do you think?

https://github.com/lucasvegi/Elixir-Code-Smells#large-code-generation

**Comment by josevalim** [comment]
Fantastic!!
