### ISSUE TITLE
Rewrite the part about spawn and spawn_link?

### ISSUE THREAD

**Issue by adolfont** [lucasvegi/Elixir-Code-Smells#15]
Wouldn't it be better and more precise, instead of writing (GenServer envy smell):

**In Elixir, processes can be primitively created by spawn/1 and spawn_link/1 functions.**

to write:

**In Elixir, processes can be primitively created by Kernel.spawn/1, Kernel.spawn/3, Kernel.spawn_link/1 and Kernel.spawn_link/3 functions.**

??

**Comment by lucasvegi** [comment]
Great suggestion! I just incorporated it in the last commit (bc15ccbf271626256d89d44e6c74ac1039c13abe).
Thanks.
