### ISSUE TITLE
Discussion: data manipulation without migrations when using releases

### ISSUE THREAD

**Issue by sbacarob** [lucasvegi/Elixir-Code-Smells#23]
Under [Data manipulation by migration](https://github.com/lucasvegi/Elixir-Code-Smells#data-manipulation-by-migration), the recommended refactoring of creating a mix task only really works if you're able to run mix tasks. Which means that if you're using releases it's not quite clear what the solution would be.

Should one create a [release task](https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-one-off-commands-eval-and-rpc)? Would that be the case even if it's a one-off thing? The mix release guide does suggest using helper modules for grouping commands that one notices one is using repeatedly.

Being a one-off thing, it may be tempting to use `eval` or `rpc` or even to open a remote iex session and manually do it. But, if the data manipulation that one needs to do gets even a little bit complicated, or if one is going to deploy to more than one environment, it may easily become error-prone.

So, what would be the best solution when using releases?

**Comment by sbacarob** [comment]
Thank you for your response! I would like to hear your thoughts on this kind of approach: https://blog.appsignal.com/2020/02/25/migrating-production-data-in-elixir.html

**Comment by josevalim** [comment]
I also believe this guide covers data migrations: https://fly.io/phoenix-files/safe-ecto-migrations/
