### ISSUE TITLE
Ranges in Elixir are lazy

### ISSUE THREAD

**Issue by josevalim** [lucasvegi/Elixir-Code-Smells#3]
Hi @lucasvegi, great work!

There is one error in the documentation of "Large messages between processes", related to large values between process:

    content: [1, 2, 3..1_000_000]

The range `3..1_000_000` is not realized in Elixir, which means the list above is actually quite small. I think the smell is correct, but not because it blocks the caller, but rather because messages are copied between processes, but even then not necessarily a smell. It is important to benchmark and be sure. :)

**Comment by lucasvegi** [comment]
Hi @josevalim , thanks for your alert!

Really the message content was too small (length 3). I modified the example in the last commit (a3ab0a9ff051440bfee6e3885b947c337b2a88f8), leaving it as follows:

```elxir
content: Enum.to_list(1..1_000_000)
```

I've also updated the problem description, incorporating your suggestion that copying the content of the large messages between processes is the kernel of the problem.

Could you confirm if I managed to improve the documentation for this smell?

**Comment by josevalim** [comment]
Beautiful!
