### ISSUE TITLE
Discussion: Untested polymorphic behavior

### ISSUE THREAD

**Issue by josevalim** [lucasvegi/Elixir-Code-Smells#8]
In my mind, the main concern with untested polymorphic behaviour is not that it raises for missing types. It is rather that you can pass inputs that have no meaning. Take the dasherize function, I can call `dasherize(URI.parse("/foo"))`. But does it really make sense to dasherize a URL? or a number? The fix is to either 1) remove the protocol call 2) add guards to restrict the protocol 3) keep the protocol but documents its consequences clearly :)

**Comment by lucasvegi** [comment]
Thanks for the note @josevalim!

I've just updated some documentation details for this smell (commit a1e07309fa2c74090a675c3cfd3631ef1e2d725d), like the refactoring example, following your observation about data types that might not make sense in polymorphic functions.

What do you think?

**Comment by josevalim** [comment]
In Elixir is not common to match or guard on a type to raise. You match on the types you do handle, like is_string and is_atom, and that’s it. So the solution would be this:

    def dasherize(atom) when is_atom(atom) do
      dasherize(Atom.to_string(atom))
    end

    def dasherize(string) when is_binary(string) do
      …implementation without to_string…
    end

**Comment by josevalim** [comment]
And the other solution is to document it uses a protocol :)

**Comment by lucasvegi** [comment]
I think now I got it (177944cec597ff01fc26280a4662f28b7b093aa6)!  :)

What do you think?

**Comment by josevalim** [comment]
Perfect!!!
